name: Build lambda dist zip

on:
  release:
    types:
      - published

jobs:
  build-lambda-dist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: npm
          cache-dependency-path: package.json
      - name: Upgrade npm
        run: npm install -g npm@10
      - name: Install dependencies
        run: npm install
      - name: Run build
        run: npm run build
        env:
          BUILD_PRE_HOOK: true
          BUILD_POST_HOOK: true
      - name: Get node version
        run: echo "NODE_VERSION=$(cat .nvmrc)" >> "$GITHUB_ENV"
      - name: Get stac-server version
        run: echo "STAC_SERVER_VERSION=$(npm pkg get version)" >> "$GITHUB_ENV"
      - name: Rename zipfiles
        run: |
          mv dist/api/api.zip stac-server-api-lambda_${STAC_SERVER_VERSION}_node-${NODE_VERSION}.zip
          mv dist/ingest/ingest.zip stac-server-ingest-lambda_${STAC_SERVER_VERSION}_node-${NODE_VERSION}.zip
          mv dist/pre-hook/pre-hook.zip stac-server-pre-hook-lambda_${STAC_SERVER_VERSION}_node-${NODE_VERSION}.zip
          mv dist/post-hook/post-hook.zip stac-server-post-hook-lambda_${STAC_SERVER_VERSION}_node-${NODE_VERSION}.zip
      - name: Add to release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags')
        with:
          files: |
            stac-server-api-lambda_${STAC_SERVER_VERSION}_node-${NODE_VERSION}.zip
            stac-server-ingest-lambda_${STAC_SERVER_VERSION}_node-${NODE_VERSION}.zip
            stac-server-pre-hook-lambda_${STAC_SERVER_VERSION}_node-${NODE_VERSION}.zip
            stac-server-post-hook-lambda_${STAC_SERVER_VERSION}_node-${NODE_VERSION}.zip

